config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'posts#index'
	resources :posts
	resources :tags, only: [:show]
	resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
	validates :name, presence: true
	has_ancestry
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	has_many :taggings
	has_many :tags, through: :taggings
	belongs_to :category
	
	validates :title, :summary, :body, presence: true

	def all_tags
		self.tags.map(&:name).join(', ')
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name.strip).first_or_create
	end
end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :posts, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

 def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end


  def index
  	@categories = Category.all
  end

  def show
    
  end


  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to categories_path, success: 'Success'
  	else
  		@categories = Category.all.order(:name)
  		flash[:danger] = 'Failure'
  		render :new
  	end
  end

  def edit
  	 @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
  	if @category.update_attributes(category_params)
  	redirect_to categories_path, success: 'Success'
  else
  	@categories = Category.all.order(:name)
  	flash[:danger] = 'Failure'
  	render :new
  	end
  end

  def destroy
  	@category.destroy

  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
  	params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post, success:'Success'
		else
		flash.now[:danger] = 'Failure'
		render :new
		end 
	end

	def edit
	end

	def update
		if @post.update_attributes(post_params)
			redirect_to @post
		else
			flash.now[:danger] = 'Failure'
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id])
		@posts = @tag.posts 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(name)
		{
			success: "alert-success",
			error: "alert-danger",
			danger: "alert-danger",
			alert: "alert-warning",
			notice: "alert-info"
		} [name.to_sym] || name
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
	<div class='alert alert-danger'>
		<h5><%= t('common.errors') %></h5>
		<ul>
			<% @category.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @category do |f| %>
	<div class='form-controll'>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class='form-group'>
		<%= f.label :parent_id %>
		<%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
	</div>


	<div class='form-group'>
		<%= f.submit 'Submit', action: @category.new_record? ? 'Create' : 'Edit', class: 'btn btn-primary' %>
		<%= link_to 'Cancel', :back, class: 'btn btn-outline-secondary' %>
	</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div class='buttons_panel'>
	<%= link_to 'New category', new_category_path, class: 'btn btn-outline-primary btn-sm'%>
</div>

<section id='categories'>
	<table class= 'table'>
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Parent</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each_with_index do |category, index| %>
			<tr>
				<td><%= index + 1 %></td>
				<td><%= category.name %></td>
				<td><%= category.parent.name if category.parent.present? %></td>
				<td>
					<%= link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
					<%= link_to 'Delete', category_path(category), method: :delete, date: {confirm: 'Delete this category?'}, class: 'btn btn-outline-primary btn-sm' %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</section>

app/views/categories/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waha40kFanBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Warhammer 40k FanBase</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= posts_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
<%= link_to 'New post', new_post_path, class: 'btn btn-outline-pimary pull-xs-left'%>
    <ul class="navbar-nav pull-xs-right">
      <% if user_signed_in?%>
      <%= link_to 'Exit', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
      <li class="nav-item active">
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        <li class="nav-item active">
        <%= link_to 'Sign up',  new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
    </div>

    <div class="container">
      <div class='row'>
        <dir class='col-md-12'>
          <% flash.each do |name, message| %>
          <div class='alert <%= bootstrap_class_for(name) %>'>
            <button class='close' data-dismiss='alert'>&times;</button>
            <%= message %>
          </div>
          <% end %>
        </dir>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-4">
          <div class='tag_cloud'>
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://noremorse-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<div class='alert alert-danger'>
		<h5><%= t('common.errors') %></h5>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
	<div class='form-controll'>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class='form-controll'>
		<%= f.label :summary %>
		<%= f.text_area :summary %>
	</div>

	<div class='form-controll'>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>

	<div class='form-controll'>
		<%= f.submit 'Save' %>
	</div>

	<div class='form-group'>
		<%= f.file_field :image %>
	</div>

	<div class='form-group'>
		<%= f.label :category_id %>
		<%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true}, class: 'form-controll' %>
	</div>

	<div class='form-group'>
		<%= f.label :all_tags %>
		<%= f.text_field :all_tags, class: 'form-controll' %>
	</div>

<% end %>

app/views/posts/_post.html.erb
<article class="post">
	<section class="post-head">
		<h2><%= link_to post.title, post_path(post) %></h2>
		<small>
			<time><%= post.created_at.to_date.strftime("%d %B %Y") %></time>
			<% if post.category.present? %>
			 | 
			<%= link_to post.category.name, post.category %>
			<% end %>
			 | 
			<%= link_to 'Edit', edit_post_path(post) %>
			 | 
			<%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Delete this post?'} %>
		</small>
	</section>

	<section class="summary clearfix">
		<div class='working'><%= image_tag post.image.url(:thumb), class: 'img-thumbnail  thumb' if post.image? %></div>
		<%= post.summary %>
	</section>

	<section class="footer-summary">
		<%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t), class: 'badge badge-primary'}.join(' ')  %>
	</section>
</article>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class='nps'>"Heresy grows from idleness"</div>

<%= render @posts %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to 'Edit', edit_post_path(@post) %>
 | 
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Delete this post?'}%>

<%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
<p><%= @post.body %></p>

<%= render 'disqus' %>

app/views/shared/_submenu.html.erb
<div class='submenu'>
	<h2>Categories</h2>
	<ul class='nav nav-pills nav-stacked'>
		<% Category.roots.each do |category| %>
		<li class='nav-item'>
			<%= link_to category.name, category, class: "nav-link #{'active' if current_page? (category_path(category))}" %>
			<% render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
		</li>
		<% end %>
	</ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class='nav nav-pills nav-stacked nested-nav'>
	<% categories.each do |category, children| %>
	<li>
		<%= link_to category.name, category, class: "nav-link #{'active' if current_page? (category_path(category))}" %>
		<% render 'shared/submenu_categories', categories: children if children.present? %>
	</li>
	<% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
	<h2> No posts </h2>
<% else %>
	<%= render @tag.posts %>
<% end %>